# language ides and syntax packsa
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'html', 'typescript']
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'jsx']
[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'jsx', 'typescript', 'tsx']
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'tsx']
hook_add = '''
  autocmd FileType typescript :set makeprg=tsc
'''
[[plugins]]
repo = 'ianks/vim-tsx'
on_ft = ['typescript', 'tsx']
[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ['elm']
[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = ['ansible']
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']
[[plugins]] # autoclose ruby end tag
repo = 'tpope/vim-endwise'
on_ft = ['ruby']
[[plugins]] # better ruby completion
repo = 'marcus/rsense'
on_ft = ['ruby']
[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = ['processing', 'arduino']
hook_add = '''
  let g:processing_fold=1
'''
# heavy
# [[plugins]]
# repo = 'tpope/vim-markdown'
# on_ft = ['markdown']
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# prettier
[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['javascript', 'typescript', 'jsx', 'tsx']
do = 'yarn install'

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'xhtml', 'jsx', 'tsx']
hook_add = '''
  let g:user_emmet_leader_key='<C-e>'
'''

# autoclose html(xhtml) tags
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'javascript', 'typescript', 'jsx', 'tsx']
hook_add = '''
  let g:closetag_filenames='*.html,*.xhtml,*.phtml,*.jsx,*.tsx,*.vue'
  let g:closetag_xhtml_filenames='*.xhtml,*.jsx,*.tsx'
  let g:closetag_filetypes='html,xhtml,phtml'
  let g:closetag_xhtml_filetypes='xhtml,jsx,tsx'
  let g:closetag_emptyTags_caseSensitive=1
  let g:closetag_shortcut='>'
  let g:closetag_close_shortcat='<leader>>'
'''

# styled-components
[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['jsx', 'tsx']

# deoplete completion sources
[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c']
[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript', 'typescript', 'jsx', 'tsx']
build = "{'mac': 'npm install -g tern', 'unix': 'npm install -g tern' }"
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
# not working
# [[plugins]]
# repo = 'mhartington/nvim-typescript'
# on_ft = ['typescript', 'tsx']
