# autosave
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
  let g:auto_save = 1
  let g:auto_save_in_insert_mode = 0
'''

# language packs
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disabled = ['elm']
'''

# language server protocol
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
if executable('docker-langserver')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'docker-langserver',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'docker-langserver --stdio']},
        \ 'whitelist': ['dockerfile'],
        \ })
endif
if executable('go-langserver')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'go-langserver',
        \ 'cmd': {server_info->['go-langserver', '-gocodecompletion']},
        \ 'whitelist': ['go'],
        \ })
endif
if executable('solargraph')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'solargraph',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'solargraph stdio']},
        \ 'initialization_options': {"diagnostics": "true"},
        \ 'whitelist': ['ruby'],
        \ })
endif
if executable('typescript-language-server')
    au User lsp_setup call lsp#register_server({
      \ 'name': 'typescript-language-server',
      \ 'cmd': { server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
      \ 'root_uri': { server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_directory(lsp#utils#get_buffer_path(), '.git/..'))},
      \ 'whitelist': ['typescript', 'javascript', 'javascript.jsx'],
      \ })
endif
'''

# auto switch filetype (too heavy)
# [[plugins]]
# repo = 'Shougo/context_filetype.vim'
# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# depends = 'context_filetype.vim'
# hook_add = '''
#   let g:precious_enable_switch_CursorMoved = {
#     \ "*" : 0
#   \}
#   let g:precious_enable_switch_CursorMoved_i = {
#     \	"*" : 0
#   \}
#   augroup test " switch when change to insert mode
#     autocmd!
#     autocmd InsertEnter * :PreciousSwitch
#     autocmd InsertLeave * :PreciousReset
#   augroup END
# '''

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'onedark',
    \ 'active': {
    \   'left': [
    \     ['mode', 'paste'],
    \     ['gitbranch', 'readonly', 'relativepath', 'modified'],
    \   ],
    \   'right': [
    \     ['percent'],
    \     ['linter_errors', 'linter_warnings'],
    \     ['fileencoding', 'filetype'],
    \   ],
    \ },
    \ 'inactive': {
    \   'left': [
    \     ['gitbranch', 'readonly', 'relativepath', 'modified'],
    \   ],
    \   'right': [
    \     ['linter_errors', 'linter_warnings'],
    \   ],
    \ },
    \ 'component_function': {
    \   'gitbranch': 'fugitive#head',
    \ },
  \ }
  let g:lightline.component_expand = {
    \  'linter_checking': 'lightline#ale#checking',
    \  'linter_warnings': 'lightline#ale#warnings',
    \  'linter_errors': 'lightline#ale#errors',
    \  'linter_ok': 'lightline#ale#ok',
    \ }
  let g:lightline.component_type = {
    \  'linter_checking': 'left',
    \  'linter_warnings': 'warning',
    \  'linter_errors': 'error',
    \  'linter_ok': 'left',
    \ }
'''
[[plugins]]
repo = 'tpope/vim-fugitive'
depends = 'lightline.vim'
[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = 'lightline.vim'

# folder tree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  autocmd StdinReadPre * let s:std_in=1
  autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  nnoremap <silent><C-n> :NERDTreeToggle<CR>
  let g:NERDTreeShowHidden=1
  let g:NERDTreeIgnore=[
    \ '\.DS_Store', '\.git$', 'node_modules', 'bower_components', '__pycache__',
    \ '\.db', '\.sqlite$', '\.rbc$', '\~$', '\.pyc', '\.idea$', '\.vscode$',
    \ '\vendor\/bundle', '\.awcache$'
  \ ]
  let g:NERDTreeDirArrows=1
  let g:NERDTreeDirArrowExpandable='▸'
  let g:NERDTreeDirArrowCollapsible='▾'
  let g:NERDTreeFileExtensionHighlightFullName=1
  let g:NERDTreeExactMatchHighlightFullName=1
  let g:NERDTreePatternMatchHighlightFullName=1
  let g:NERDTreeLimitedSyntax=1
  " syntax highlight
  let s:brown = "905532"
  let s:aqua =  "3AFFDB"
  let s:blue = "689FB6"
  let s:darkBlue = "44788E"
  let s:purple = "834F79"
  let s:lightPurple = "834F79"
  let s:red = "AE403F"
  let s:beige = "F5C06F"
  let s:yellow = "F09F17"
  let s:orange = "D4843E"
  let s:darkOrange = "F16529"
  let s:pink = "CB6F6F"
  let s:salmon = "EE6E73"
  let s:green = "8FAA54"
  let s:lightGreen = "31B53E"
  let s:white = "FFFFFF"
  let s:rspec_red = 'FE405F'
  let s:git_orange = 'F54D27'
  let g:NERDTreeExtensionHighlightColor = {}
  let g:NERDTreeExactMatchHighlightColor = {}
  let g:NERDTreePatternMatchHighlightColor = {}
'''
[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
depends = 'nerdtree'
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = 'nerdtree'
hook_add = '''
  let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }
'''
# slow
# [[plugins]]
# repo = 'ryanoasis/vim-devicons'
# depends = 'nerdtree'

# show line that has git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_async=1
'''

# asynchronous loading
[[plugins]]
repo = 'Shougo/vimproc'
build = "{ \
  \ 'windows' : 'make -f make_mingw32.mak',
  \ 'cygwin' : 'make -f make_cygwin.mak',
  \ 'mac' : 'make -f make_mac.mak',
  \ 'unix' : 'make -f make_unix.mak',
\ }"

# completion
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'nvim-yarp'
depends = 'vim-hug-neovim-rpc'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#file#enable_buffer_path = 1
  inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
'''
[[plugins]]
repo = 'Shougo/neco-syntax'
depends = 'deoplete.nvim'
# [[plugins]] # not working
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# build = 'sh install.sh'
# depends = 'vim-lsp'
# depends = 'deoplete.nvim'

# fuzzy finder
[[plugins]]
repo = '/usr/local/opt/fzf'
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  nnoremap <C-t> :Files<CR>
  let g:fzf_layout = { 'down': '~40%' }
  let g:fzf_buffers_jump=1
'''

# grep
[[plugins]]
repo = 'mhinz/vim-grepper'
hook_add = '''
  nnoremap <C-g> :Grepper -tool ag -highlight<cr>
'''

# comment out
[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
  nmap <C-c> <Plug>(caw:i:toggle)
  vmap <C-c> <Plug>(caw:i:toggle)
'''

# highlight trailing spaces
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# highlight replacing charcters
[[plugins]]
repo = 'osyo-manga/vim-over'

# linters
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_lint_on_enter=1
  let g:ale_lint_on_save=1
  let g:ale_lint_on_text_changed=0
  let g:ale_sign_column_always=1
  let g:ale_linters = {
    \ 'css': ['stylelint', 'prettier'],
    \ 'erb': ['erb'],
    \ 'go': ['gofmt', 'goimports'],
    \ 'html': ['HTMLHint'],
    \ 'haml': ['haml-lint'],
    \ 'javascript': ['eslint', 'flow', 'prettier', 'prettier-eslint'],
    \ 'json': ['jsonlint'],
    \ 'Markdown': ['prettier', 'textlint'],
    \ 'Python': ['pylint'],
    \ 'ruby': ['rubocop', 'solargraph'],
    \ 'sass': ['sass-lint'],
    \ 'scss': ['sass-lint'],
    \ 'SQL': ['sqlint'],
    \ 'swift': ['swiftlint'],
    \ 'typescript': ['tsserver', 'prettier'],
    \ 'vim': ['vint'],
    \ 'yaml': ['yamllint'],
    \ }
  let g:ale_sign_error='E'
  let g:ale_sign_warning='W'
  let g:ale_echo_msg_error_str='E'
  let g:ale_echo_msg_warning_str='W'
  let g:ale_echo_msg_format='[%linter%] %s (%severity%)'
  let g:ale_statusline_format=['E %d', 'W %d', '']
  let g:ale_open_list=1
  let g:ale_set_loclist=0
  let g:ale_set_quickfix=1 " use QuickFix
  let g:ale_keep_list_window_open=0
  let g:ale_javascript_prettier_use_local_config=1
'''

# visualize colors
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

# surround by cs
[[plugins]]
repo = 'tpope/vim-surround'
