# autosave
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = 'let g:autosave = 1'

# language packs
[[plugins]]
repo = 'sheerun/vim-polyglot'

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'onedark',
    \ 'active': {
    \   'left': [
    \     [ 'mode', 'paste' ],
    \     [ 'gitbranch', 'readonly', 'relativepath', 'modified']
    \   ],
    \   'right': [
    \     [ 'percent' ],
    \     [ 'linter_errors', 'linter_warnings' ],
    \     [ 'fileencoding', 'filetype' ]
    \   ]
    \ },
    \ 'inactive': {
    \   'left': [
    \     [ 'gitbranch', 'readonly', 'relativepath', 'modified' ]
    \   ],
    \   'right': [
    \     [ 'linter_errors', 'linter_warnings' ],
    \   ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'fugitive#head'
    \ },
  \ }
'''
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'maximbaz/lightline-ale'
hook_add = '''
  let g:lightline.component_expand = {
    \  'linter_checking': 'lightline#ale#checking',
    \  'linter_warnings': 'lightline#ale#warnings',
    \  'linter_errors': 'lightline#ale#errors',
    \  'linter_ok': 'lightline#ale#ok',
    \ }
  let g:lightline.component_type = {
    \     'linter_checking': 'left',
    \     'linter_warnings': 'warning',
    \     'linter_errors': 'error',
    \     'linter_ok': 'left',
    \ }
'''

# folder tree
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# show line that has git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'

# asynchronous loading
[[plugins]]
repo = 'Shougo/vimproc'
build = "{ \
  \ 'windows' : 'make -f make_mingw32.mak',
  \ 'cygwin' : 'make -f make_cygwin.mak',
  \ 'mac' : 'make -f make_mac.mak',
  \ 'unix' : 'make -f make_unix.mak',
\ }"

# completion
[[plugins]]
repo = 'Shougo/neocomplete'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# fuzzy finder
[[plugins]]
repo = '/usr/local/opt/fzf'
[[plugins]]
repo = 'junegunn/fzf.vim'

# grep
[[plugins]]
repo = 'mhinz/vim-grepper'

# comment out
[[plugins]]
repo = 'tyru/caw.vim.git'

# highlight trailing spaces
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# highlight replacing charcters
[[plugins]]
repo = 'osyo-manga/vim-over'

# language ides and syntax packsa
[[plugins]]
repo = 'fatih/vim-go'
[[plugins]]
repo = 'pangloss/vim-javascript'
[[plugins]]
repo = 'mxw/vim-jsx'
[[plugins]]
repo = 'leafgarland/typescript-vim'
[[plugins]]
repo = 'ianks/vim-tsx'
[[plugins]]
repo = 'pearofducks/ansible-vim'
[[plugins]]
repo = 'vim-ruby/vim-ruby'
[[plugins]] # autoclose ruby end tag
repo = 'tpope/vim-endwise'
[[plugins]] # better ruby completion
repo = 'marcus/rsense'
[[plugins]]
repo = 'sophacles/vim-processing'
[[plugins]] # dependency of vim-markdown
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'plasticboy/vim-markdown'

# linters
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'prettier/vim-prettier'
do = 'yarn install'

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'

# autoclose html(xhtml) tags
[[plugins]]
repo = 'alvan/vim-closetag'

# visualize colors
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
