# language ides and syntax packsa
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
  let g:go_fmt_autosave = 1
  let g:go_fmt_command = "goimports"
  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
  let g:go_metalinter_enabled = 0
  let g:go_code_completion_enabled = 0
  let g:go_gocode_unimported_packages = 0
  let g:go_def_mode='gopls'
  let g:go_info_mode='gopls'
  let g:go_highlight_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_function_parameters = 1
  let g:go_highlight_methods = 1
'''
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
[[plugins]] # requires typescript, typescript-language-server
repo = 'ryanolsonx/vim-lsp-javascript'
on_ft = ['javascript', 'javascript.jsx']
[[plugins]]
repo = 'ianks/vim-tsx'
on_ft = ['typescript', 'typescript.tsx']
[[plugins]] # requires typescript typescript-language-server
repo = 'ryanolsonx/vim-lsp-typescript'
on_ft = ['typescript', 'typescript.tsx']
[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ['elm']
[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = ['ansible']
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']
# [[plugins]] # autoclose ruby end tag
# repo = 'tpope/vim-endwise'
# on_ft = ['ruby']
[[plugins]] # better ruby completion
repo = 'marcus/rsense'
on_ft = ['ruby']
[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = ['processing', 'arduino']
hook_add = '''
  let g:processing_fold=1
'''
# heavy
# [[plugins]]
# repo = 'tpope/vim-markdown'
# on_ft = ['markdown']
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# prettier
[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['javascript', 'typescript', 'javascript.jsx', 'typescript.tsx']
do = 'yarn install'

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'xhtml', 'javascript.jsx', 'typescript.tsx']
hook_add = '''
  let g:user_emmet_leader_key='<C-e>'
'''

# autoclose html(xhtml) tags
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'javascript', 'typescript', 'javascript.jsx', 'typescript.tsx']
hook_add = '''
  let g:closetag_filenames='*.html,*.xhtml,*.phtml,*.jsx,*.tsx,*.vue'
  let g:closetag_xhtml_filenames='*.xhtml,*.jsx,*.tsx'
  let g:closetag_filetypes='html,xhtml,phtml'
  let g:closetag_xhtml_filetypes='xhtml,jsx,tsx'
  let g:closetag_emptyTags_caseSensitive=1
  let g:closetag_shortcut='>'
  let g:closetag_close_shortcat='<leader>>'
'''

# styled-components
[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript.jsx', 'typescript.tsx']

# graphql
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

# Swift
[[plugins]]
repo = 'ryanolsonx/vim-lsp-swift'
on_ft = ['swift']
