# language packs
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled=['elm']
'''

# toggle comments
[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
nnoremap <C-c> <Plug>(caw:hatpos:toggle)
vnoremap <C-c> <Plug>(caw:hatpos:toggle)
'''

# change operator by s+a/d/r
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
hook_add = '''
nnoremap <silent>sa <Plug>(operator-surround-append)
nnoremap <silent>sd <Plug>(operator-surround-delete)
nnoremap <silent>sr <Plug>(operator-surround-replace)
'''

# improved autoread
[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events'

# for vim-delve
[[plugins]]
repo = 'benmills/vimux'

# autoclose parenthesis
# conflicted <CR> imap with coc.nvim
# [[plugins]]
# repo = 'cohama/lexima.vim'

# wrap/unwrap arguments,lists,dict
[[plugins]]
repo = 'FooSoft/vim-argwrap'
hook_add = '''
nnoremap <C-a> :ArgWrap<CR>
let g:argwrap_tail_comma = 1
'''
