# language packs
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled=['elm']
'''

# toggle comments
[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
nmap <C-c> <Plug>(caw:hatpos:toggle)
vmap <C-c> <Plug>(caw:hatpos:toggle)
'''

# auto close parentheses
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# change operator by s+a/d/r
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
hook_add = '''
nmap <silent>sa <Plug>(operator-surround-append)
nmap <silent>sd <Plug>(operator-surround-delete)
nmap <silent>sr <Plug>(operator-surround-replace)
'''

# improved autoread
[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events'

# for vim-delve
[[plugins]]
repo = 'benmills/vimux'
