# language packs
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['elm']
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# asynchronous execution
[[plugins]]
repo = 'Shougo/vimproc'
build = '''
\ "{
  \ 'windows' : 'make -f make_mingw32.mak',
  \ 'cygwin' : 'make -f make_cygwin.mak',
  \ 'mac' : 'make -f make_mac.mak',
  \ 'unix' : 'make -f make_unix.mak',
\ }"
'''

# comment out
[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
nmap <C-c> <Plug>(caw:i:toggle)
vmap <C-c> <Plug>(caw:i:toggle)
'''

# auto close parentheses
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# change operator by s+a/d/r
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
hook_add = '''
map <silent>sa <Plug>(operator-surround-append)
map <silent>sd <Plug>(operator-surround-delete)
map <silent>sr <Plug>(operator-surround-replace)
'''

# improved autoread
[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events'

# execute command directly from Vim
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
map <C-q> :QuickRun<CR>
'''

# overwrite f
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
" Move to char (overwrite f)
map  f <Plug>(easymotion-bd-f)
nmap f <Plug>(easymotion-overwin-f)

" Move to line (overwrite L)
map L <Plug>(easymotion-bd-jk)
nmap L <Plug>(easymotion-overwin-line)

" Move to word
map  W <Plug>(easymotion-bd-w)
nmap W <Plug>(easymotion-overwin-w)

let g:EasyMotion_smartcase=1
'''
