# language packs
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['elm']
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# show line that has git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_async=1
'''

# asynchronous execution
[[plugins]]
repo = 'Shougo/vimproc'
build = '''
\ "{
  \ 'windows' : 'make -f make_mingw32.mak',
  \ 'cygwin' : 'make -f make_cygwin.mak',
  \ 'mac' : 'make -f make_mac.mak',
  \ 'unix' : 'make -f make_unix.mak',
\ }"
'''

# comment out
[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
nmap <C-c> <Plug>(caw:i:toggle)
vmap <C-c> <Plug>(caw:i:toggle)
'''

# highlight trailing spaces
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# highlight replacing charcters
[[plugins]]
repo = 'osyo-manga/vim-over'

# visualize colors
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

# auto close parentheses
[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
let g:lexima_enable_basic_rules=1
let g:lexima_enable_newline_rules=1
'''

# change operator by s+a/d/r
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
hook_add = '''
map <silent>sa <Plug>(operator-surround-append)
map <silent>sd <Plug>(operator-surround-delete)
map <silent>sr <Plug>(operator-surround-replace)
'''

# improved autoread
[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events'

# execute command directly from Vim
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
map <C-q> :QuickRun<CR>
'''
