# color
[[plugins]]
repo = 'navarasu/onedark.nvim'
hook_add = '''
lua <<EOF
require('onedark').setup {
  toggle_style_key = '<C-e>',
    style = 'warmer'
}
require('onedark').load()
EOF
'''

# show line that has git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_async=1
'''

# visualize colors
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

# highlight trailing spaces
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

# indent
# not working
# [[plugins]]
# repo = 'lukas-reineke/indent-blankline.nvim'
# hook_add = '''
# lua <<EOF
# require("indent_blankline").setup {
#   show_current_context = true,
#   show_current_context_start = true,
# }
# EOF
# '''

# syntax highlight
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
do = '''
:TSUpdate
'''
hook_add = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "go", "typescript", "javascript", "dart", "ruby", "proto", "yaml", "json", "bash", "html", "css", "make", "vim", "lua" },
  sync_install = false,
  highlight = {
    enable = true,
    disable = { "dart" },
  },
}
EOF
'''

# sticky scroll
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-context'
hook_add = '''
lua <<EOF
require'treesitter-context'.setup{
  enable = true, -- Enable this plugin (Can be enabled/disabled later via commands)
  max_lines = 0, -- How many lines the window should span. Values <= 0 mean no limit.
  min_window_height = 0, -- Minimum editor window height to enable context. Values <= 0 mean no limit.
  line_numbers = true,
  multiline_threshold = 20, -- Maximum number of lines to collapse for a single context line
  trim_scope = 'outer', -- Which context lines to discard if `max_lines` is exceeded. Choices: 'inner', 'outer'
  mode = 'topline',  -- Line used to calculate context. Choices: 'cursor', 'topline'
  -- Separator between context and content. Should be a single character string, like '-'.
  -- When separator is set, the context will only show up when there are at least 2 lines above cursorline.
  separator = nil,
  zindex = 20, -- The Z-index of the context window
}
EOF
'''
