# color
[[plugins]]
repo = 'navarasu/onedark.nvim'
hook_add = '''
lua <<EOF
require('onedark').setup({
  toggle_style_key = '<C-e>',
    style = 'warmer'
})
require('onedark').load()
EOF
'''

# show line that has git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_async=1
'''

# visualize colors
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

# highlight trailing spaces
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

# indent
# [[plugins]]
# repo = 'shellRaining/hlchunk.nvim'
# hook_add = '''
# lua <<EOF
# require('hlchunk').setup({})
# EOF
# '''

# syntax highlight
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
do = '''
:TSUpdate
'''
hook_add = '''
lua <<EOF
require('nvim-treesitter.configs').setup({
  ensure_installed = { "go", "typescript", "javascript", "dart", "ruby", "proto", "yaml", "json", "bash", "html", "css", "make", "vim", "lua" },
  sync_install = false,
  highlight = {
    enable = true,
    disable = { "dart" },
  },
})
EOF
'''

# sticky scroll
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-context'
hook_add = '''
lua <<EOF
require('treesitter-context').setup({
  enable = true,
})
EOF
'''

# scroll bar
[[plugins]]
repo = 'dstein64/nvim-scrollview'
hook_add = '''
lua <<EOF
require('scrollview').setup()
EOF
'''
