# show line that has git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_async=1
'''

# visualize colors
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

# highlight trailing spaces
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# indent
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char_list=['|']
let g:indentLine_setConceal=0
'''

# syntax highlight
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
do = '''
:TSUpdate
'''
hook_add = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "go", "typescript", "javascript", "dart", "ruby", "proto", "yaml", "json", "bash", "html", "css", "make" },
  sync_install = false,
  highlight = {
    enable = true,
    disable = { "dart" },
  },
}
EOF
'''

# indent guides
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup=1
'''
