# fuzzy finder
# requires `$ brew install fzf`
[[plugins]]
repo = '~/.fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
nnoremap <C-f> :Files<CR>
nnoremap <C-g> :Rg<Space>
nnoremap <C-b> :Buffers<CR>
let g:fzf_layout = { 'down': '~40%' }
let g:fzf_buffers_jump=1
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case --hidden ".shellescape(<q-args>), 1, <bang>0)
'''

[[plugins]]
repo = 'antoinemadec/coc-fzf'
depends_on = [
  'junegunn/fzf.vim',
  'neoclide/coc.nvim',
]
hook_add = '''
nnoremap <C-d> :CocFzfList dianostics<CR>
nnoremap <C-t> :CocFzfList outline<CR>
nnoremap <silent> <space>c :<C-u>CocFzfList commands<CR>
'''
