# linters
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_lint_on_enter=1
let g:ale_lint_on_save=1
let g:ale_lint_on_text_changed=0
let g:ale_sign_column_always=1
let g:ale_disable_lsp = 1
let g:ale_linters = {
  \ 'bash': ['shellcheck'],
  \ 'css': ['stylelint', 'prettier'],
  \ 'dart': ['dartanalyzer'],
  \ 'dockerfile': ['hadolint'],
  \ 'erb': ['erb'],
  \ 'go': ['golint', 'golangci-lint'],
  \ 'graphql': ['eslint'],
  \ 'html': ['HTMLHint'],
  \ 'haml': ['haml-lint'],
  \ 'javascript': ['eslint'],
  \ 'json': ['jq'],
  \ 'make': ['checkmake'],
  \ 'markdown': ['prettier', 'textlint'],
  \ 'python': ['pylint'],
  \ 'ruby': ['rubocop', 'solargraph'],
  \ 'rust': ['cargo', 'rustfmt'],
  \ 'sass': ['sass-lint'],
  \ 'scss': ['sass-lint'],
  \ 'SQL': ['sqlint', 'sqlfmt'],
  \ 'swift': ['swiftlint'],
  \ 'typescript': ['eslint'],
  \ 'vim': ['vint'],
  \ 'yaml': ['yamllint'],
  \ }
let g:ale_sign_error='E'
let g:ale_sign_warning='W'
let g:ale_echo_msg_error_str='E'
let g:ale_echo_msg_warning_str='W'
let g:ale_echo_msg_format='[%linter%] %s (%severity%)'
let g:ale_statusline_format=['E %d', 'W %d', '']
let g:ale_open_list=1
let g:ale_set_loclist=0
let g:ale_set_quickfix=1 " use QuickFix
let g:ale_keep_list_window_open=0
let g:ale_javascript_prettier_use_local_config=1
'''

