[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
nnoremap <silent><C-n> :NERDTreeToggle<CR>
let g:NERDTreeShowHidden=1
let g:NERDTreeIgnore=[
  \ '\.DS_Store', '\.git$', 'node_modules', 'bower_components', '__pycache__',
  \ '\.db', '\.sqlite$', '\.rbc$', '\~$', '\.pyc', '\.idea$', '\.vscode$',
  \ '\vendor\/bundle', '\.awcache$'
\ ]
let g:NERDTreeQuitOnOpen=1
let g:NERDTreeAutoDeleteBuffer=1
let g:NERDTreeMinimalUI=1
'''

# syntax highlight
# [[plugins]]
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
# depends = 'nerdtree'

# git plugin
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = 'nerdtree'

# icons
# [[plugins]]
# repo = 'ryanoasis/vim-devicons'
# depends = 'nerdtree'
# hook_add = '''
# let g:WebDevIconsUnicodeDecorateFolderNodes = 1
# let g:WebDevIconsNerdTreeBeforeGlyphPadding = ''
# let g:WebDevIconsNerdTreeAfterGlyphPadding = ''
# '''
