# actions
# a: action
# m: move
# c: copy
# D: delete
# l: expand
# ?: open help
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
let g:fern#disable_default_mappings=1
nnoremap <silent><C-n> :Fern . -drawer -reveal=% -toggle -stay<CR>
function! s:init_fern() abort
  nmap <buffer><nowait> l <Plug>(fern-action-expand)
  nmap <buffer><nowait> h <Plug>(fern-action-collapse)
  nmap <buffer><nowait> D <Plug>(fern-action-remove)
  nmap <buffer><nowait> c <Plug>(fern-action-copy)
  nmap <buffer><nowait> m <Plug>(fern-action-move)
  nmap <buffer><nowait> N <Plug>(fern-action-new-file)
  nmap <buffer><nowait> <Return> <Plug>(fern-action-open)
endfunction
augroup fern-custom
  autocmd! *
  autocmd FileType fern call s:init_fern()
augroup END
" show hidden files by default
let g:fern#default_hidden=1
'''

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
hook_add = '''
" Disable listing ignored files/directories
let g:fern_git_status#disable_ignored=1
" Disable listing untracked files
let g:fern_git_status#disable_untracked=1
" Disable listing status of submodules
let g:fern_git_status#disable_submodules=1
" Disable listing status of directories
let g:fern_git_status#disable_directories=1
'''
depends = ['fern.vim']

[[plugins]]
repo = 'LumaKernel/fern-mapping-reload-all.vim'
hook_add = '''
function s:init_fern_mapping_reload_all()
  nmap <buffer> R <Plug>(fern-action-reload:all)
endfunction
augroup my-fern-mapping-reload-all
  autocmd! *
  autocmd FileType fern call s:init_fern_mapping_reload_all()
augroup END
'''
depends = ['fern.vim']
