# status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \ 'colorscheme': 'onedark',
  \ 'active': {
  \   'left': [
  \     ['mode', 'paste'],
  \     ['gitbranch', 'readonly', 'relativepath', 'modified'],
  \   ],
  \   'right': [
  \     ['percent'],
  \     ['linter_errors', 'linter_warnings'],
  \     ['fileencoding', 'filetype'],
  \   ],
  \ },
  \ 'inactive': {
  \   'left': [
  \     ['readonly', 'relativepath', 'modified'],
  \   ],
  \   'right': [
  \     ['linter_errors', 'linter_warnings'],
  \   ],
  \ },
  \ 'component_function': {
  \   'gitbranch': 'GitStatus',
  \ },
\ }
function GitStatus() abort
  return get(g:, 'coc_git_status', '')
endfunction
'''
