[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
lua << EOF
require('lualine').setup({
  options = {
    theme = 'onedark',
    colored = true,
    path = 1,
  },
  sections = {
    lualine_b = {'diff', 'diagnostics'},
    lualine_x = {'filetype'},
    lualine_y = {},
  },
})
EOF
'''
