[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_add = '''
  let g:rustfmt_autosave = 1
'''
[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = ['ansible']
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']
[[plugins]] # better ruby completion
repo = 'marcus/rsense'
on_ft = ['ruby']
[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = ['processing', 'arduino']
hook_add = '''
  let g:processing_fold=1
'''
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown']
build = 'cd app & yarn install'
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'xhtml', 'javascript.jsx', 'typescript.tsx']
hook_add = '''
  let g:user_emmet_leader_key='<C-e>'
'''

# autoclose html(xhtml) tags
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'javascript', 'typescript', 'javascript.jsx', 'typescript.tsx']
hook_add = '''
  let g:closetag_filenames='*.html'
  let g:closetag_xhtml_filenames='*.jsx,*.tsx,*.vue'
  let g:closetag_filetypes='html'
  let g:closetag_xhtml_filetypes='jsx,tsx,javascript.jsx,typescript.tsx,vue'
  let g:closetag_emptyTags_caseSensitive=1
  let g:closetag_shortcut='>'
'''

# graphql
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']
