[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_add = '''
let g:goimports_local = 'github.com/ebkn,github.com/mesh-i,github.dena.jp/Takasho'
'''

# [[plugins]]
# repo = 'sebdah/vim-delve'
# on_ft = ['go']
# hook_add = '''
# let g:delve_use_vimux=1
# autocmd FileType go nmap <silent> ;d :DlvToggleBreakpoint<CR>
# '''
