[[plugins]]
repo = 'mattn/vim-goimports'
hook_add = '''
let g:goimports_cmd='gofmt'
'''

# [[plugins]]
# repo = 'sebdah/vim-delve'
# on_ft = ['go']
# hook_add = '''
# let g:delve_use_vimux=1
# autocmd FileType go nmap <silent> ;d :DlvToggleBreakpoint<CR>
# '''
