# JavaScript
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = [
  'javascript',
  'javascript.jsx',
  'javascriptreact',
]

# TypeScript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = [
  'typescript',
  'typescript.tsx',
  'typescriptreact',
]

# vue
[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

# styled-components
# [[plugins]]
# repo = 'styled-components/vim-styled-components'
# on_ft = [
#   'javascript.jsx',
#   'typescript.tsx',
#   'typescriptreact',
#   'javascriptreact',
#   'javascript',
#   'typescript',
# ]

# elm
[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ['elm']
