# ansible
[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = ['ansible']

# processing
[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = ['processing', 'arduino']
hook_add = '''
let g:processing_fold=1
'''

# autoclose html(xhtml) tags
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'javascript', 'typescript', 'javascript.jsx', 'typescript.tsx']
hook_add = '''
let g:closetag_filenames='*.html'
let g:closetag_xhtml_filenames='*.jsx,*.tsx,*.vue'
let g:closetag_filetypes='html'
let g:closetag_xhtml_filetypes='jsx,tsx,javascript.jsx,typescript.tsx,vue'
let g:closetag_emptyTags_caseSensitive=1
let g:closetag_shortcut='>'
'''

# graphql
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# css
[[plugins]]
repo = 'ap/vim-css-color'
