# ansible
[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = ['ansible']

# processing
[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = ['processing', 'arduino']
hook_add = '''
let g:processing_fold=1
'''

# autoclose html(xhtml) tags
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'javascript', 'typescript', 'javascript.jsx', 'typescript.tsx', 'javascriptreact', 'typescriptreaact']
hook_add = '''
let g:closetag_filenames='*.html'
let g:closetag_xhtml_filenames='*.jsx,*.tsx,*.vue'
let g:closetag_filetypes='html'
let g:closetag_xhtml_filetypes='jsx,tsx,javascript.jsx,typescript.tsx,vue'
let g:closetag_emptyTags_caseSensitive=1
let g:closetag_shortcut='>'
'''

# graphql
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql', 'javascript', 'javascriptreact', 'typescript', 'typescriptreact']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# css
[[plugins]]
repo = 'ap/vim-css-color'

# c++, proto
# run :ClangFormat for format
[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['cpp', 'c', 'proto', 'protobuf']
hook_add = '''
let g:clang_format#detect_style_file=1
let g:clang_format#auto_format=1
'''

# indent guides
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_ft = ['yaml', 'json', 'python']
